### Q1. What are the benefits of the built-in array package, if any?

The array package in Python offers benefits such as:

- Memory efficiency
- Efficient numeric operations
- Typed arrays
- Interoperability with low-level languages

### Q2. What are some of the array package&#39;s limitations?

- Fixed size: The size of an array is fixed at the time of creation and cannot be dynamically resized.
- Limited functionality: Arrays in the array package have limited functionality compared to other data structures like lists or NumPy arrays.
- Lack of built-in methods: The array package lacks some of the built-in methods and functionalities available in other data structures.
- Type restrictions: The elements in an array must be of the same type, which can be restrictive in certain situations where heterogeneous data is required.
- Lack of high-level operations: The array package does not provide high-level operations and functions commonly found in other data structures or libraries like NumPy.

### Q3. Describe the main differences between the array and numpy packages.

- Numpy provides advanced data structures like ndarrays, which allow for efficient storage and manipulation of multi-dimensional arrays, while the array package has more limited support for array operations.
- Numpy offers a wide range of mathematical and statistical functions specifically designed for working with arrays, making it easier to perform complex calculations and data analysis.
- Numpy has better performance optimizations and efficient memory management techniques, resulting in faster execution times compared to the array package.
- Numpy has a larger user community and extensive documentation, providing a rich ecosystem of libraries and tools that build on top of the numpy functionality.

### Q4. Explain the distinctions between the empty, ones, and zeros functions.

- The empty function in numpy creates an array without initializing its elements to any specific values. The array will contain arbitrary values that are determined by the current state of memory. It is a fast way to allocate memory for an array without incurring the overhead of initializing its elements.

- The ones function in numpy creates an array filled with the value 1. It takes the shape of the desired array as an argument and creates an array of that shape with all elements set to 1. This function is useful when you need to initialize an array with all elements having the same value.

- The zeros function in numpy creates an array filled with the value 0. Similar to the ones function, it takes the shape of the desired array as an argument and creates an array of that shape with all elements set to 0. This function is useful when you need to initialize an array with all elements initialized to zero.

In [3]:
import numpy as np

# Creating an empty array
empty_arr = np.empty((3, 3))
print("Empty Array:")
print(empty_arr)

# Creating an array filled with ones
ones_arr = np.ones((2, 2))
print("Array of Ones:")
print(ones_arr)

# Creating an array filled with zeros
zeros_arr = np.zeros((4, 4))
print("Array of Zeros:")
print(zeros_arr)


Empty Array:
[[6.92005805e-310 6.92005805e-310 7.30331611e+011]
 [1.06196101e+007 3.13845500e+021 4.56372573e+016]
 [5.91190555e-302 6.12608227e-302 3.73525915e-301]]
Array of Ones:
[[1. 1.]
 [1. 1.]]
Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

In [5]:
import numpy as np

def generate_value(x, y):
    return x * y

arr = np.fromfunction(generate_value, (3, 3))
print(arr)


[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In the fromfunction function of NumPy, the callable argument refers to a function that is used to generate the values for the elements of the new array. The fromfunction function creates a new array by executing the provided function with coordinates as inputs.

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

When a NumPy array is combined with a single-value operand (a scalar) through addition (+), the scalar value is broadcasted to match the shape of the array, and element-wise addition is performed between the array and the scalar.

In [6]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

n = 10

result = A + n

print(result)


[[11 12 13]
 [14 15 16]]


### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Yes, array-to-scalar operations can use combined operation-assign operators such as += or *=. The outcome of using these operators is that the operation is applied to each element of the array.

In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = 2

a *= b
print(a)


[2 4 6]


### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?



Yes, a NumPy array can contain fixed-length strings. When you allocate a longer string to a fixed-length string array, NumPy will truncate the string to fit the specified length.

In [11]:
import numpy as np

# Create a fixed-length string array of length 5
arr = np.array(["apple", "banana", "cherry"], dtype='S5')

# Assign a longer string to one of the elements
arr[1] = "strawberry"

print(arr)


[b'apple' b'straw' b'cherr']


### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

When you combine two NumPy arrays using an operation like addition (+) or multiplication (*), the operation is performed element-wise. This means that the corresponding elements of the arrays are combined according to the operation.

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


### Q10. What is the best way to use a Boolean array to mask another array?

The best way to use a Boolean array to mask another array in NumPy is by applying the Boolean array as an indexing mask. This allows you to select elements from the array based on the corresponding values in the Boolean array.

In [1]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a Boolean mask
mask = np.array([True, False, True, False, True])

# Mask the array using the Boolean mask
masked_arr = arr[mask]

print(masked_arr)


[1 3 5]


### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [2]:
import numpy as np
import statistics
import math

data = [1, 2, 3, 4, 5]

# Using NumPy
std_dev_numpy = np.std(data)

# Using the statistics module
std_dev_statistics = statistics.stdev(data)

# Manual calculation
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_dev_manual = math.sqrt(variance)

print("Standard Deviation (NumPy):", std_dev_numpy)
print("Standard Deviation (statistics module):", std_dev_statistics)
print("Standard Deviation (manual calculation):", std_dev_manual)


Standard Deviation (NumPy): 1.4142135623730951
Standard Deviation (statistics module): 1.5811388300841898
Standard Deviation (manual calculation): 1.4142135623730951


### 12. What is the dimensionality of a Boolean mask-generated array?

The dimensionality of a Boolean mask-generated array is the same as the dimensionality of the original array on which the mask is applied. The Boolean mask serves as a filter to select elements from the original array based on certain conditions. The resulting Boolean mask-generated array will have the same number of dimensions as the original array, but its shape may be different depending on the elements selected by the mask.